# Generated by Django 4.0.3 on 2022-04-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_bread_id_alter_cheese_id_alter_sauce_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
