# Generated by Django 2.2 on 2022-04-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('in_use', 'in_use'), ('deleted', 'deleted')], default='in_use', max_length=50)),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.Bread')),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.Cheese')),
                ('sauces', models.ManyToManyField(related_name='sandwiches', to='ingredients.Sauce')),
                ('toppings', models.ManyToManyField(related_name='sandwiches', to='ingredients.Topping')),
            ],
            options={
                'db_table': 'sandwiches',
            },
        ),
    ]
