# Generated by Django 4.0.3 on 2022-04-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0002_alter_sandwich_id_alter_sandwich_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
