# Generated by Django 4.0.3 on 2022-04-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0003_alter_sandwich_name_alter_sandwich_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandwich',
            name='price',
        ),
    ]
